# Generated by Django 4.0.4 on 2022-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoinStash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=200)),
                ('coin_symbol', models.CharField(max_length=200)),
                ('coin_name', models.CharField(max_length=200)),
            ],
        ),
    ]
