# Generated by Django 4.0.4 on 2022-04-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoinStash', '0002_coinlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_api_id',
            field=models.CharField(default='no-id', max_length=200),
        ),
        migrations.AlterField(
            model_name='coin',
            name='avg_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='coin',
            name='balance',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='coin',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
