# Generated by Django 4.0.4 on 2022-04-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoinStash', '0004_alter_coin_coin_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_fee',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BUY'), (2, 'SELL')], default=1),
        ),
    ]
